### ISSUE TITLE
PyCharm 直接运行爬龙

### ISSUE THREAD

**Issue by KevinZhangt** [spencer404/PyLoom#2]
我想请问一下，如何在 PyCharm 直接运行爬龙呢,我直接在__main__.py运行,会报错：
ModuleNotFoundError: No module named '__main__.entry'; '__main__' is not a package
谢谢！

**Comment by speng4096** [comment]
添加个运行配置吧，就可以用绿三角按钮运行了 。
1. 进入 `Run > Edit Configurations`
2. 点左上角加号，选 `Python`
3. 在`Script parameters` 处填写 `-m pyloom run -s /path/to/spiders/DouBanBooks`
