### ISSUE TITLE
并夕夕爬不了了

### ISSUE THREAD

**Issue by mtpdx** [spencer404/PyLoom#4]

**Comment by Flytutu** [comment]
拼多多会限制访问速度，需要使用代理，若没有使用代理，需要降低访问速度
修改默认爬取速度，将PinDuoDuo/configs.py文件中的interval属性修改一下，修改为3能够正常运行

**Comment by MKe090** [comment]
代理的格式是？

**Comment by Flytutu** [comment]
README.md对代理进行了说明，目前框架支持蘑菇代理和米扑代理，你根据需要可以自己添加代理驱动，目前拼多多存在一定的问题，这周末进行修复。
