### ISSUE TITLE
拼多多

### ISSUE THREAD

**Issue by yzw1** [spencer404/PyLoom#5]
拼多多的不行了，找不到了

**Comment by Kevenyf** [comment]
平多多爬不了了 用这个框架

**Comment by Flytutu** [comment]
测试了一下确实爬取不了了，这周末进行修复，我们会长期更新爬虫策略，同时对框架进行更新，近期预计添加JD的爬虫策略。

**Comment by nakebull** [comment]
有进展吗

**Comment by Herny88** [comment]
求破解拼多多URL中的anti_content大法

**Comment by SergioJune** [comment]
https://github.com/SergioJune/Spider-Crack-JS/tree/master/pinduoduo

**Comment by MongoliaDick** [comment]
拼多多爬不出来内容了？

**Comment by Flytutu** [comment]
#6

**Comment by Flytutu** [comment]
#6 添加了拼多多网页版爬虫
